### ISSUE TITLE
Viết SQL queries cho node backend server (PostgresQL Client Query)

### ISSUE THREAD

**Issue by rxng8** [forummlcb/topdup#35]
Như tiêu đề, e đề xuất sẽ làm SQL query cho những functionality sau, bởi vì mỗi functionality sẽ có một tập các tổ hợp về điều kiện, mình sẽ chia ra thành từng loại query, sau đó create tổ hợp dựa trên query gốc:
- [x] 1) User query:
  - [x]  `allUsers.sql`: Return the information of all users (with blocks if necessary).
  - [x]  `userVote.sql`: Given an user id, return all the article pairs that this user has voted (with blocks if necessary).
  - [x]  `articleVote.sql`: Given an article id, return all the pairs where this article is in, with the vote count (positive and negative) from each unique user (with blocks if necessary).
  - [x]  `activeUsers.sql`: Given an integer `k`, return `k` top users that voted the most.
- [x] 2) Similarity reports query:
  - [x] `allArticles.sql`: Get all articles, every field (with blocks if necessary).
  - [x] `topKSim.sql`: Given an integer `k`, return a list of `k` pairs of articles that have the highest similarity score.
  - [x] `tSim.sql`: Given a float threshold `t`, return a list of all pairs of articles that have the similarity score greater than `t` (with blocks if necessary).
  - [x] `domainSim.sql`: Given a domain, return a list of all pairs in which one in two articles have that domain (with blocks if necessary).
  - [x] `titleSim.sql`: Given an article title, return a list of all pairs in which one in two articles have that title (with blocks if necessary).
  - [x] `dateSim.sql`: Given an article date, return a list of all pairs in which both two articles have that date (with blocks if necessary).
-------
Mọi người có bổ sung thêm, edit, hay muốn làm với mình thì cứ tự nhiên và comment ở dưới ạ.

**Comment by anhhd2703** [comment]
Mục 1 - 2 -3 - 4, mình thấy bạn là "all" thì mình không hiểu ý bạn lắm. Bạn có phân trang không ạ hay lấy "all".
Như topdup.xyz mình không nhầm thì là đang lấy data rất nhiều.

**Comment by rxng8** [comment]
cái sql này sẽ được executed bằng postgresql client, sau khi fetch được data rồi thì phân trang như thế nào là việc của client.

**Comment by anhhd2703** [comment]
Mình đang hiểu là nếu bạn làm thế thì có 1k data bạn sẽ gửi hết cho client rồi client từ đó tự phân trang phải không ạ?
Nếu làm như thế thì nó performance rất là tệ.
Nên thực hiện phân trang luôn khi query (đấy là những gì mình làm với mongoDB).

**Comment by phamcong** [comment]
@rxng8 với size của data < 10k records thì không có vấn đề gì về hiệu năng.

Query 4 có thể sẽ phải thêm param vào, để giới hạn số bản ghi trả về (theo package 100/ 200 hoặc 500 items). Trên page SimilarityReport, việc phân trang ở client side chỉ tốt nếu số lượng trả về ít, nếu lớn thì không nên.

Liên quan tới SimilarityReport, bên cạnh số items trả về, cần thêm vào trong quey với các param "titleSearchTerm", "dateRange", "domain".

**Comment by rxng8** [comment]
@phamcong @anhhd2703 cảm ơn hai anh. E edit issue r đấy ạ. Có j a cứ góp ý ạ
